### ISSUE TITLE
TLS certificate created via tls-certificates relation can't be decoded by nginx ingress controller

### ISSUE THREAD

**Issue by mthaddon** [canonical/nginx-ingress-integrator-operator#123]
### Bug Description

Currently we create a TLS certificate via the tls-certificates relation with a private key per https://github.com/canonical/nginx-ingress-integrator-operator/blob/main/src/tls_relation.py#L206. But we're not making that private key available to kubernetes, so the nginx-ingress controller can't decode the certificate, and falls back to the default certificate.

We should either remove the private key (traefik doesn't use one when it creates its certificate per https://github.com/canonical/traefik-k8s-operator/blob/565cd91d99545876cd4affeddd1055b9981791cb/lib/charms/observability_libs/v0/cert_handler.py#L218) or find a way to pass it to the nginx-ingress controller so that the certificate can be used

### To Reproduce

1. Deploy the charm and relate to httprequest-lego-k8s
2. Confirm the requested certificate can't be decoded by nginx-ingress controller

### Environment

Openstack, Juju 3.1.7.

### Relevant log output

```shell
# From the ingress controller logs
W0416 07:03:07.096578       6 backend_ssl.go:45] Error obtaining X.509 certificate: unexpected error creating SSL Cert: certificate and private key does not have a matching public key: tls: failed to parse private key
```

**Comment by gregnebu** [comment]
After a quick analysis, the issue comes from the fact that the private keys is encrypted using a passphrase and stored in the secret encrypted. Since nginx ingress controller doesn't seem to support getting the passphrase to decrypt the private key, nginx-ingress-integrator should ensure that when the secret is created, the private key is stored decrypted.

Suggestion of fix:
- Since the tls-certificate library doesn't provide a way to decrypt a private key, I'd create a method within the `tls-reation` module to decrypt a given private key (which will require adding `cryptography` as a dependency
```python
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey

def load_encrypted_private_key(encrypted_private_key: bytes, password: str) -> RSAPrivateKey:
    """
    Load and decrypt an RSA private key that is PEM-encoded and encrypted.
    
    Args:
        encrypted_private_key: The encrypted PEM file.
        password: Password used to encrypt the key.
    
    Returns:
        The decrypted RSA private key.
    """

    private_key = serialization.load_pem_private_key(
        encrypted_private_key,
        password=password
    )

    return private_key
```
- And then build a dict of decrypted keys from the `keys` attribute of `_tls` in the following method: https://github.com/canonical/nginx-ingress-integrator-operator/blob/main/src/charm.py#L169 to pass it to the `IngressDefinitionEssence`
