### ISSUE TITLE
Add support for proxy-send-timeout and proxy-connect-timeout annotations

### ISSUE THREAD

**Issue by kelkawi-a** [canonical/nginx-ingress-integrator-operator#164]
### Enhancement Proposal

As described in the title, these would be useful charm configuration parameters to expose. They have the same type as the `proxy-read-timeout` configuration parameter on the charm.

**Comment by weiiwang01** [comment]
Yes, no problem, I think this is a very useful feature. Let me create a pull request to add it. Thanks!

**Comment by kelkawi-a** [comment]
@weiiwang01 Could we also add the [`keep-alive`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#keep-alive) annotation to this request? Any idea when it could be merged?

**Comment by gaborbk** [comment]
Adding my +1 to this enhancement request, it would be really useful for my team as well.

**Comment by weiiwang01** [comment]
> @weiiwang01 Could we also add the [`keep-alive`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#keep-alive) annotation to this request? Any idea when it could be merged?

Yes, let me see if I can find anyone to review the pull request.
For the `[keep-alive](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#keep-alive)` attribute, I believe it's a configmap rather than an annotation. This means it can only be changed by someone with access to the ingress Kubernetes namespace.

**Comment by weiiwang01** [comment]
Revision 130 (amd64) and revision 131 (arm64) released with the `proxy-send-timeout` and `proxy-connect-timeout` configuration.
